---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: A collection of Backstage templates for OTC Backstage
spec:
  targets:
    - ./zuul-repo/template.yaml
    - ./helpcenter-service/template.yaml
